### ISSUE TITLE
fpga sdr hardware

### ISSUE THREAD

**Issue by fpgasdr** [nmk456/fpga-sdr#1]
Hi,

I can't figure out how this code was tested and in witch platform?.

just saw picture of the ATREB215-XPRO eval board but no other hardware.

can yo elaborate?

thanks.

**Comment by eljuligallego** [comment]
it seem you use the deca board from intel but no quartus project is in the repository

**Comment by nmk456** [comment]
Yes, the project will use a Deca board and a custom AT86RF215 board, but it's not finished so the quartus project doesn't exist and the PCB hasn't been built. The code has only been tested in simulations so far, and not as an entire system.
